local term = require ("term")
local component = require ("component")
local c = component.computer
local Re = component.nc_salt_fission_reactor

print("Obtaining Reactor Data")
  ReO = Re.isReactorOn()
  c.beep(200,0.3)
  ReX = Re.getLengthX()
  ReY = Re.getLengthY()
  ReZ = Re.getLengthZ()
  c.beep(200,0.3)
  ReHS =  Re.getHeatStored()
  ReHC = Re.getHeatCapacity()
  c.beep(200,0.3)
  ReCR = Re.getCoolingRate()
  ReNHR = Re.getNetHeatingRate()
  c.beep(200,0.3)
  ReCE = Re.getCoolingEfficiency()
  c.beep(200,0.3)
  ReNV = Re.getNumberOfVessels()
  ReNH = Re.getNumberOfHeaters()
  c.beep(800)
print("")
print("Displaying Data")
print("")
  if (ReO == true) then
    print("Reactor is Online")
  else
    print("Reactor is Offline")
  end
print("")
print("Lenght / Height / Depth")
print(ReX,ReY,ReZ)
print("")
print("Max Temp vs. Current Temp")
print(ReHC,ReHS)
print("")
print("Coolers vs. Vessels")
print(ReNH,ReNV)
print("")
print("Cooling Rate / %  Efficiency / Net Heat Gen")
print(ReCR,ReCE*100,ReNHR)
print("")
c.beep()
c.beep()